version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8001:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
